### ISSUE TITLE
Error with compilation

### ISSUE THREAD

**Issue by browey** [Joona70/fortnite-cheat-source-public#1]
![image](https://user-images.githubusercontent.com/30350026/72666288-eee38f80-3a10-11ea-8c2e-385c6e324584.png)

**Comment by browey** [comment]
dame solucion?

**Comment by Joona70** [comment]
if you are too stupid to compile one fucking lib, you dont deserve to use this cheat.

**Comment by xliquid808** [comment]
you don't even have to compile there's a compiled version under releases xd
