### ISSUE TITLE
How would i load the driver?

### ISSUE THREAD

**Issue by ThonkPT** [Joona70/fortnite-cheat-source-public#13]
so i built everything but when i run the exe it prints "Load Driver first, exiting..." and closes, how would i load said driver though and which driver is it

**Comment by ThonkPT** [comment]
also if someone is thinking about asking me to share the built version or tell you how to build it dont everyone is gonna most likely ignore you

**Comment by Joona70** [comment]
send me your discord.

**Comment by ThonkPT** [comment]
ThonkPT#6430 also whats yours so i know who to add

**Comment by Joona70** [comment]
added jondefin

**Comment by dschaf** [comment]
im having problems compiling the driver

**Comment by dschaf** [comment]
how do i load it i got it to compile

**Comment by dschaf** [comment]
nevermind got the cheat fully functional
