### ISSUE TITLE
can i make p2c with this pls?

### ISSUE THREAD

**Issue by Dull1337** [Joona70/fortnite-cheat-source-public#16]
i have 5$ only i need money am i allowed to make p2c??

**Comment by NathanPrivate** [comment]
> i have 5$ only i need money am i allowed to make p2c??

This does not make sense why shall you make a paid cheat out of a public source i expected better from you dull

**Comment by Dull1337** [comment]
> > i have 5$ only i need money am i allowed to make p2c??
> 
> This does not make sense why shall you make a paid cheat out of a public source i expected better from you dull

sorry i am poor my maven stopped making sales i need money 😭

**Comment by Volxy7331** [comment]
my ass cheeks hurt

**Comment by Koha001** [comment]
Hum , we will find a solution for you 👍

**Comment by Joona70** [comment]
do whatever you want, i dont care.
